#!/usr/bin/env bash
bin=`dirname $0`
bin=`cd "$bin"; pwd`
APP_HOME=`cd "$bin"/..;pwd`
echo $APP_HOME
readonly MASTER_JARS="$(ls "$APP_HOME"/lib/{{name}}-*.jar 2> /dev/null | tr "\n" :)"
CLASSPATH="$APP_HOME/lib/*:$MASTER_JARS"
java -Duser.timezone=Asia/Shanghai -DAPP_HOME=${APP_HOME} -Dlogback.configurationFile=$APP_HOME/conf/logback.xml -cp "$CLASSPATH" rocks.pho.apps.{{name}} "$@"
